#!/bin/sh

# A pre-commit hook that ensures a Rust project contains no errors or warnings.

# Fail the entire hook immediately if any of the commands fails.
set -e

# Set the profiles to use for all of the cargo-based tools that supports it.
profiles="dev release"

# Ensure the following commands does not emit any errors or warnings.
# - Compilers: cargo build
# - Linters: cargo clippy and cargo machette
# - Documentation Generator: cargo doc
# - Unit Tests and Integration Tests: cargo test
for profile in $profiles
do
    echo "Profile $profile"
    echo "Cargo Build"
    RUSTFLAGS="-D warnings" cargo build --profile $profile --all-targets
    echo
    echo "Cargo Clippy"
    RUSTFLAGS="-D warnings" cargo clippy --profile $profile --all-targets
    echo
    echo "Cargo Doc"
    RUSTDOCFLAGS="-D warnings" cargo doc --profile $profile
    echo
    echo "Cargo Machette"
    cargo machete --with-metadata
    echo
    echo "Cargo Test"
    RUSTFLAGS="-D warnings" cargo test --profile $profile --all-targets -- --nocapture
done
