#!/bin/sh

# A pre-commit hook that ensures a Rust project with CPython bindings (update
# line 30 so it cds to the bindings folder) contains no errors or warnings.

# Fail the entire hook immediately if any of the commands fails.
set -e

# Ensure the following commands does not emit any errors or warnings.
# - Compilers: cargo build and python3 -m pip install .
# - Linters: cargo clippy and cargo machette
# - Documentation Generator: cargo doc
# - Unit Tests and Integration Tests: cargo test and python3 -m unittest
echo "Cargo Build"
RUSTFLAGS="-D warnings" cargo build --all-targets
echo
echo "Cargo Clippy"
RUSTFLAGS="-D warnings" cargo clippy --all-targets
echo
echo "Cargo Doc"
RUSTDOCFLAGS="-D warnings" cargo doc
echo
echo "Cargo Machette"
cargo machete --with-metadata
echo
echo "Cargo Test"
RUSTFLAGS="-D warnings" cargo test --all-targets
echo
echo "Python Build"
cd crates/modelardb_compression_python
python3 -m pip install .
echo
echo "Python Test"
python3 -m unittest
